<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ImageLib" Version="*" />
    <PackageReference Include="TesterLib" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>
<ItemGroup>

  <None Remove="Assets\*.png" />

  <Content Include="Assets\*.png">

    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>

  </Content>

</ItemGroup>
<ItemGroup>
  <Content Update="Assets\BlueTrophy.png">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Update="Assets\Box.png">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Update="Assets\GreenTrophy.png">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Update="Assets\Player.png">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Update="Assets\RedTrophy.png">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Update="Assets\Wall.png">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  <Content Update="Assets\YellowTrophy.png">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>
</Project>

