<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ImageLib" Version="*" />
    <PackageReference Include="TesterLib" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Dyes.Examples" />
  </ItemGroup>
</Project>

