<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ImageLib" Version="*" />
    <PackageReference Include="TesterLib" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lightning.Implementation\Lightning.Implementation.csproj" />
  </ItemGroup>
</Project>

