resources:
  repositories:
  - repository: problem
    type: git
    name: Problem.Bricks
    ref: main

trigger:
  - main

extends:
  template: /.azuredevops/student-pipeline.yml@problem
  parameters:
    debug: false

